# Generated by Django 4.1.6 on 2023-03-22 00:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0004_question_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
